export type ClientMenuItem = {
  name: string;
  description: string;
  price: string;
  image: string;
  section: string;
  tag?: string;
};

export type ClientCategory = {
  id: string;
  name: string;
  eyebrow: string;
  description: string;
  cover: string;
  items: ClientMenuItem[];
};

const photos = {
  soup: "/menu-images/soup.webp",
  chickenSoup: "/owner-menu/soups/chicken-soup.webp",
  vegSoup: "/owner-menu/soups/veg-soup.webp",
  hotSourSoup: "/owner-menu/soups/hot-and-sour-soup.webp",
  manchowSoup: "/owner-menu/soups/manchow-soup.webp",
  vegStarters: "/menu-images/veg-starters.webp",
  onionPakoda: "/owner-menu/veg-starters/onion-pakoda.webp",
  vegPakoda: "/owner-menu/veg-starters/veg-pakoda.webp",
  crispyCorn: "/owner-menu/veg-starters/crispy-corn.webp",
  babyCornChilli: "/owner-menu/veg-starters/baby-corn-chilli.webp",
  vegManchurian: "/owner-menu/veg-starters/veg-manchurian.webp",
  paneerChilli: "/owner-menu/veg-starters/paneer-chilli.webp",
  paneerManchurian: "/owner-menu/veg-starters/paneer-manchurian.webp",
  paneer65: "/owner-menu/veg-starters/paneer-65.webp",
  crispyPaneerPakoda: "/owner-menu/veg-starters/crispy-paneer-pakoda.webp",
  chickenStarters: "/menu-images/chicken-starters.webp",
  crispyChickenPakoda: "/owner-menu/non-veg-starters/crispy-chicken-pakoda.webp",
  chickenDryFryPakora: "/owner-menu/non-veg-starters/chicken-dry-fry-pakora.webp",
  lemonChicken: "/owner-menu/non-veg-starters/lemon-chicken.webp",
  chickenManchurian: "/owner-menu/non-veg-starters/chicken-manchurian.webp",
  chickenInflakes: "/owner-menu/non-veg-starters/chicken-inflakes.webp",
  chickenChilli: "/owner-menu/non-veg-starters/chicken-chilli.webp",
  chickenLollipop: "/owner-menu/non-veg-starters/chicken-lollipop.webp",
  crispyHoneyChicken: "/owner-menu/non-veg-starters/crispy-honey-chicken.webp",
  chicken65: "/owner-menu/non-veg-starters/chicken-65.webp",
  momos: "/menu-images/momos.webp",
  vegFriedMomos: "/owner-menu/momos/veg-fried-momos.webp",
  vegChilliMomos: "/owner-menu/momos/veg-chilli-momos.webp",
  noodles: "/menu-images/noodles.webp",
  paneerNoodles: "/owner-menu/noodles-bites/noodles/paneer-noodles.webp",
  eggNoodles: "/owner-menu/noodles-bites/noodles/egg-noodles.webp",
  chickenNoodles: "/owner-menu/noodles-bites/noodles/chicken-noodles.webp",
  mixVegNoodles: "/owner-menu/noodles-bites/noodles/mix-veg-noodles.webp",
  cnpSpecialNoodles: "/owner-menu/noodles-bites/noodles/cnp-special-noodles.webp",
  streetBites: "/menu-images/street-bites.webp",
  classicFrenchFries: "/owner-menu/noodles-bites/fries/classic-french-fries.webp",
  periPeriFrenchFries: "/owner-menu/noodles-bites/fries/peri-peri-french-fries.webp",
  potatoChilli: "/owner-menu/noodles-bites/fries/potato-chilli.webp",
  honeyPotatoChilli: "/owner-menu/noodles-bites/fries/honey-potato-chilli.webp",
  alooTikkiBurger: "/owner-menu/noodles-bites/burgers/aloo-tikki-burger.webp",
  vegCheeseBurger: "/owner-menu/noodles-bites/burgers/veg-cheese-burger.webp",
  paneerBurger: "/owner-menu/noodles-bites/burgers/paneer-burger.webp",
  cafeBites: "/menu-images/cafe-bites.webp",
  whiteSaucePasta: "/owner-menu/noodles-bites/pasta/white-sauce-alfredo-pasta.webp",
  redSaucePasta: "/owner-menu/noodles-bites/pasta/red-sauce-alfredo-pasta.webp",
  pastaChickenAddOn: "/owner-menu/noodles-bites/pasta/chicken-add-on.webp",
  pavBhaji: "/owner-menu/noodles-bites/pav-bhaji/pav-bhaji.webp",
  butterMasalaPavBhaji: "/owner-menu/noodles-bites/pav-bhaji/butter-masala-pav-bhaji.webp",
  extraPav: "/owner-menu/noodles-bites/pav-bhaji/extra-pav.webp",
  vegSandwich: "/owner-menu/noodles-bites/sandwiches/veg-sandwich.webp",
  vegGrilledSandwich: "/owner-menu/noodles-bites/sandwiches/veg-grilled-sandwich.webp",
  paneerGrilledSandwich: "/owner-menu/noodles-bites/sandwiches/paneer-grilled-sandwich.webp",
  chickenGrillSandwich: "/owner-menu/noodles-bites/sandwiches/chicken-grill-sandwich.webp",
  extraCheese: "/owner-menu/noodles-bites/sandwiches/extra-cheese.webp",
  vegSoupyMaggi: "/owner-menu/noodles-bites/maggi/veg-soupy-maggi.webp",
  eggSoupyMaggi: "/owner-menu/noodles-bites/maggi/egg-soupy-maggi.webp",
  chickenSoupyMaggi: "/owner-menu/noodles-bites/maggi/chicken-soupy-maggi.webp",
  cnpSpecialMaggi: "/owner-menu/noodles-bites/maggi/cnp-special-maggi.webp",
  friedRice: "/menu-images/fried-rice.webp",
  vegFriedRice: "/owner-menu/fried-rice/veg-fried-rice.webp",
  paneerFriedRice: "/owner-menu/fried-rice/paneer-fried-rice.webp",
  eggFriedRice: "/owner-menu/fried-rice/egg-fried-rice.webp",
  mixVegFriedRice: "/owner-menu/fried-rice/mix-veg-fried-rice.webp",
  chickenFriedRice: "/owner-menu/fried-rice/chicken-fried-rice.webp",
  cnpSpecialFriedRice: "/owner-menu/fried-rice/cnp-special-fried-rice.webp",
  jeeraRice: "/owner-menu/fried-rice/jeera-rice.webp",
  schezwanRiceAddOn: "/owner-menu/fried-rice/schezwan-add-on.webp",
  mushroomRiceAddOn: "/owner-menu/fried-rice/mushroom-add-on.webp",
  butterRiceAddOn: "/owner-menu/fried-rice/butter-add-on.webp",
  singapuriRiceAddOn: "/owner-menu/fried-rice/singapuri-add-on.webp",
  eggRiceAddOn: "/owner-menu/fried-rice/egg-add-on.webp",
  chickenRiceAddOn: "/owner-menu/fried-rice/chicken-add-on.webp",
  biryani: "/menu-images/biryani.webp",
  curries: "/menu-images/curries.webp",
  kadaiPaneer: "/owner-menu/main-course/curries/kadai-paneer.webp",
  paneerMasala: "/owner-menu/main-course/curries/paneer-masala.webp",
  paneerButterMasala: "/owner-menu/main-course/curries/paneer-butter-masala.webp",
  mutterPaneer: "/owner-menu/main-course/curries/mutter-paneer.webp",
  kadaiMushroom: "/owner-menu/main-course/curries/kadai-mushroom.webp",
  mushroomPaneerButterMasala: "/owner-menu/main-course/curries/mushroom-paneer-butter-masala.webp",
  chickenMasala: "/owner-menu/main-course/curries/chicken-masala.webp",
  chickenButterMasala: "/owner-menu/main-course/curries/chicken-butter-masala.webp",
  eggCurry: "/owner-menu/main-course/curries/egg-curry.webp",
  rotiSalad: "/menu-images/roti-salad.webp",
  plainTawaRoti: "/owner-menu/main-course/roti/plain-tawa-roti.webp",
  butterTawaRoti: "/owner-menu/main-course/roti/butter-tawa-roti.webp",
  lachhaParatha: "/owner-menu/main-course/roti/lachha-paratha.webp",
  tortillaWrapRoti: "/owner-menu/main-course/roti/tortilla-wrap-roti.webp",
  greenSalad: "/owner-menu/main-course/salads/green-salad.webp",
  onionSalad: "/owner-menu/main-course/salads/onion-salad.webp",
  hotDrinks: "/menu-images/hot-drinks.webp",
  coldDrinks: "/menu-images/cold-drinks.webp",
  milkTea: "/owner-menu/drinks-desserts/drinks/milk-tea.webp",
  masalaMilkTea: "/owner-menu/drinks-desserts/drinks/masala-milk-tea.webp",
  blackTea: "/owner-menu/drinks-desserts/drinks/black-tea.webp",
  cappuccinoCoffee: "/owner-menu/drinks-desserts/drinks/cappuccino-coffee.webp",
  chocolateCappuccino: "/owner-menu/drinks-desserts/drinks/chocolate-cappuccino.webp",
  coldCoffee: "/owner-menu/drinks-desserts/drinks/cold-coffee.webp",
  chocolateColdCoffee: "/owner-menu/drinks-desserts/drinks/chocolate-cold-coffee.webp",
  oreoColdCoffee: "/owner-menu/drinks-desserts/drinks/oreo-cold-coffee.webp",
  oreoMilkShake: "/owner-menu/drinks-desserts/drinks/oreo-milk-shake.webp",
  vanillaMilkShake: "/owner-menu/drinks-desserts/drinks/vanilla-milk-shake.webp",
  chocolateMilkShake: "/owner-menu/drinks-desserts/drinks/chocolate-milk-shake.webp",
  butterscotchMilkShake: "/owner-menu/drinks-desserts/drinks/butterscotch-milk-shake.webp",
  icedCoke: "/owner-menu/drinks-desserts/drinks/iced-coke.webp",
  masalaCoke: "/owner-menu/drinks-desserts/drinks/masala-coke.webp",
  freshLimeJuice: "/owner-menu/drinks-desserts/drinks/fresh-lime-juice.webp",
  mixDryFruitShake: "/owner-menu/drinks-desserts/drinks/mix-dry-fruit-shake.webp",
  kajuAnjeerShake: "/owner-menu/drinks-desserts/drinks/kaju-anjeer-shake.webp",
  bananaMilkShake: "/owner-menu/drinks-desserts/drinks/banana-milk-shake.webp",
  mangoMilkShake: "/owner-menu/drinks-desserts/drinks/mango-milk-shake.webp",
  sweetLassi: "/owner-menu/drinks-desserts/drinks/sweet-lassi.webp",
  desserts: "/menu-images/desserts.webp",
  gulabJamunIceCream: "/owner-menu/drinks-desserts/desserts/gulab-jamun-with-ice-cream.webp",
  vanillaIceCream: "/owner-menu/drinks-desserts/desserts/vanilla-ice-cream.webp",
  chocolateIceCream: "/owner-menu/drinks-desserts/desserts/chocolate-ice-cream.webp",
  butterscotchIceCream: "/owner-menu/drinks-desserts/desserts/butterscotch-ice-cream.webp",
};

const dish = (
  name: string,
  price: number,
  image: string,
  section: string,
  tag?: string,
): ClientMenuItem => ({
  name,
  price: String(price),
  image,
  section,
  tag,
  description:
    tag === "Add-on"
      ? `Optional ${name.toLowerCase()} for your order.`
      : `A freshly prepared favourite from our ${section.toLowerCase()} menu.`,
});

export const clientCategories: ClientCategory[] = [
  {
    id: "soups-starters",
    name: "Soups & Starters",
    eyebrow: "Start with something delicious",
    description: "Comforting soups, crisp vegetarian bites, chicken starters and momos.",
    cover: photos.chickenSoup,
    items: [
      dish("Veg Soup", 108, photos.vegSoup, "Soup", "Veg"),
      dish("Chicken Soup", 128, photos.chickenSoup, "Soup", "Non-Veg"),
      dish("Manchow Customization", 28, photos.manchowSoup, "Soup Extra", "Add-on"),
      dish("Hot & Sour Customization", 18, photos.hotSourSoup, "Soup Extra", "Add-on"),

      dish("Onion Pakoda", 118, photos.onionPakoda, "Veg Starters", "Veg"),
      dish("Veg Pakoda", 148, photos.vegPakoda, "Veg Starters", "Veg"),
      dish("Crispy Corn", 178, photos.crispyCorn, "Veg Starters", "Veg"),
      dish("Baby Corn Chilli", 178, photos.babyCornChilli, "Veg Starters", "Veg"),
      dish("Veg Manchurian", 158, photos.vegManchurian, "Veg Starters", "Veg"),
      dish("Paneer Chilli", 178, photos.paneerChilli, "Veg Starters", "Veg"),
      dish("Paneer Manchurian", 178, photos.paneerManchurian, "Veg Starters", "Veg"),
      dish("Paneer 65", 198, photos.paneer65, "Veg Starters", "Veg"),
      dish("Crispy Paneer Pakoda", 178, photos.crispyPaneerPakoda, "Veg Starters", "Veg"),

      dish("Crispy Chicken Pakoda", 198, photos.crispyChickenPakoda, "Non-Veg Starters", "Non-Veg"),
      dish("Chicken Dry-Fry / Pakora", 178, photos.chickenDryFryPakora, "Non-Veg Starters", "Non-Veg"),
      dish("Lemon Chicken", 198, photos.lemonChicken, "Non-Veg Starters", "Non-Veg"),
      dish("Chicken Manchurian", 188, photos.chickenManchurian, "Non-Veg Starters", "Non-Veg"),
      dish("Chicken Inflakes", 208, photos.chickenInflakes, "Non-Veg Starters", "Non-Veg"),
      dish("Chicken Chilli", 188, photos.chickenChilli, "Non-Veg Starters", "Non-Veg"),
      dish("Chicken Lollipop", 208, photos.chickenLollipop, "Non-Veg Starters", "Non-Veg"),
      dish("Crispy Honey Chicken", 198, photos.crispyHoneyChicken, "Non-Veg Starters", "Non-Veg"),
      dish("Chicken 65", 208, photos.chicken65, "Non-Veg Starters", "Non-Veg"),

      dish("Veg Fried Momos", 88, photos.vegFriedMomos, "Momos", "Veg"),
      dish("Veg Chilli Momos", 108, photos.vegChilliMomos, "Momos", "Veg"),
      dish("Chicken Momo", 109, "", "Momos", "Non-Veg"),
      dish("Chicken Chilli Momo", 139, "", "Momos", "Non-Veg"),
    ],
  },
  {
    id: "noodles-bites",
    name: "Noodles & Bites",
    eyebrow: "Quick, hot and satisfying",
    description: "Noodles, burgers, fries, pasta, pav bhaji, sandwiches and soupy Maggi.",
    cover: photos.mixVegNoodles,
    items: [
      dish("Veg Hakka Noodle", 109, "", "Noodles", "Veg"),
      dish("Paneer Noodles", 148, photos.paneerNoodles, "Noodles", "Veg"),
      dish("Egg Noodles", 148, photos.eggNoodles, "Noodles", "Egg"),
      dish("Chicken Noodles", 158, photos.chickenNoodles, "Noodles", "Non-Veg"),
      dish("Mix Veg Noodles", 168, photos.mixVegNoodles, "Noodles", "Veg"),
      dish("CNP Special Noodles", 178, photos.cnpSpecialNoodles, "Noodles", "Special"),
      dish("Schezwan Noodle Add-on", 28, "", "Noodle Variant", "Add-on"),
      dish("Butter Garlic Noodle Add-on", 28, "", "Noodle Variant", "Add-on"),
      dish("Mushroom Noodle Add-on", 28, "", "Noodle Variant", "Add-on"),
      dish("Butter Noodle Add-on", 28, "", "Noodle Variant", "Add-on"),
      dish("Singapuri Noodle Add-on", 38, "", "Noodle Variant", "Add-on"),
      dish("Egg Noodle Add-on", 18, "", "Noodle Variant", "Add-on"),
      dish("Chicken Noodle Add-on", 28, "", "Noodle Variant", "Add-on"),

      dish("Classic French Fries", 108, photos.classicFrenchFries, "Fries & Burgers", "Veg"),
      dish("Peri Peri French Fries", 128, photos.periPeriFrenchFries, "Fries & Burgers", "Veg"),
      dish("Potato Chilli", 138, photos.potatoChilli, "Fries & Burgers", "Veg"),
      dish("Honey Potato Chilli", 148, photos.honeyPotatoChilli, "Fries & Burgers", "Veg"),
      dish("Aloo Tikki Burger", 78, photos.alooTikkiBurger, "Fries & Burgers", "Veg"),
      dish("Veg Cheese Burger", 98, photos.vegCheeseBurger, "Fries & Burgers", "Veg"),
      dish("Paneer Burger", 118, photos.paneerBurger, "Fries & Burgers", "Veg"),
      dish("Burger Extra Cheese", 24, photos.extraCheese, "Burger Extra", "Add-on"),

      dish("Alfredo White Sauce Pasta", 178, photos.whiteSaucePasta, "Pasta"),
      dish("Alfredo Red Sauce Pasta", 187, photos.redSaucePasta, "Pasta"),
      dish("Pasta Chicken Add-on", 38, photos.pastaChickenAddOn, "Pasta Variant", "Add-on"),
      dish("Pav Bhaji", 108, photos.pavBhaji, "Pav Bhaji", "Veg"),
      dish("Butter Masala Pav Bhaji", 128, photos.butterMasalaPavBhaji, "Pav Bhaji", "Veg"),
      dish("Extra Pav", 18, photos.extraPav, "Pav Bhaji Extra", "Add-on"),
      dish("Pav Bhaji Extra Cheese", 18, photos.extraCheese, "Pav Bhaji Extra", "Add-on"),
      dish("Veg Sandwich", 88, photos.vegSandwich, "Sandwich", "Veg"),
      dish("Veg Grilled Sandwich", 98, photos.vegGrilledSandwich, "Sandwich", "Veg"),
      dish("Paneer Grilled Sandwich", 108, photos.paneerGrilledSandwich, "Sandwich", "Veg"),
      dish("Chicken Grill Sandwich", 148, photos.chickenGrillSandwich, "Sandwich", "Non-Veg"),
      dish("Sandwich Extra Cheese", 24, photos.extraCheese, "Sandwich Extra", "Add-on"),
      dish("Veg Soupy Maggi", 118, photos.vegSoupyMaggi, "Maggi", "Veg"),
      dish("Egg Soupy Maggi", 128, photos.eggSoupyMaggi, "Maggi", "Egg"),
      dish("Chicken Soupy Maggi", 148, photos.chickenSoupyMaggi, "Maggi", "Non-Veg"),
      dish("CNP Special Maggi", 158, photos.cnpSpecialMaggi, "Maggi", "Special"),
    ],
  },
  {
    id: "rice-biryani",
    name: "Rice & Biryani",
    eyebrow: "Comfort in every grain",
    description: "Wok-tossed fried rice, flavour upgrades and fragrant biryani.",
    cover: photos.chickenFriedRice,
    items: [
      dish("Veg Fried Rice", 128, photos.vegFriedRice, "Fried Rice", "Veg"),
      dish("Paneer Fried Rice", 148, photos.paneerFriedRice, "Fried Rice", "Veg"),
      dish("Egg Fried Rice", 148, photos.eggFriedRice, "Fried Rice", "Egg"),
      dish("Mix Veg Fried Rice", 168, photos.mixVegFriedRice, "Fried Rice", "Veg"),
      dish("Chicken Fried Rice", 148, photos.chickenFriedRice, "Fried Rice", "Non-Veg"),
      dish("CNP Special Fried Rice", 188, photos.cnpSpecialFriedRice, "Fried Rice", "Special"),
      dish("Jeera Rice", 128, photos.jeeraRice, "Fried Rice", "Veg"),
      dish("Schezwan Rice Add-on", 28, photos.schezwanRiceAddOn, "Rice Variant", "Add-on"),
      dish("Butter Garlic Rice Add-on", 28, "", "Rice Variant", "Add-on"),
      dish("Mushroom Rice Add-on", 28, photos.mushroomRiceAddOn, "Rice Variant", "Add-on"),
      dish("Butter Rice Add-on", 28, photos.butterRiceAddOn, "Rice Variant", "Add-on"),
      dish("Singapuri Rice Add-on", 38, photos.singapuriRiceAddOn, "Rice Variant", "Add-on"),
      dish("Egg Rice Add-on", 28, photos.eggRiceAddOn, "Rice Variant", "Add-on"),
      dish("Chicken Rice Add-on", 28, photos.chickenRiceAddOn, "Rice Variant", "Add-on"),
      dish("Veg Biryani", 149, "", "Biryani", "Veg"),
      dish("Egg Biryani", 169, "", "Biryani", "Egg"),
      dish("Chicken Biryani", 199, "", "Biryani", "Non-Veg"),
    ],
  },
  {
    id: "main-course",
    name: "Main Course",
    eyebrow: "Indian favourites",
    description: "Rich paneer, mushroom and chicken curries with roti and fresh salads.",
    cover: photos.kadaiPaneer,
    items: [
      dish("Kadai Paneer", 218, photos.kadaiPaneer, "Indian Main Course", "Veg"),
      dish("Paneer Masala", 238, photos.paneerMasala, "Indian Main Course", "Veg"),
      dish("Paneer Butter Masala", 228, photos.paneerButterMasala, "Indian Main Course", "Veg"),
      dish("Mutter Paneer", 238, photos.mutterPaneer, "Indian Main Course", "Veg"),
      dish("Kadai Mushroom", 228, photos.kadaiMushroom, "Indian Main Course", "Veg"),
      dish("Mushroom Paneer Butter Masala", 258, photos.mushroomPaneerButterMasala, "Indian Main Course", "Veg"),
      dish("Chicken Masala", 268, photos.chickenMasala, "Indian Main Course", "Non-Veg"),
      dish("Chicken Butter Masala", 278, photos.chickenButterMasala, "Indian Main Course", "Non-Veg"),
      dish("Egg Curry", 148, photos.eggCurry, "Indian Main Course", "Egg"),
      dish("Plain Tawa Roti (4 pcs)", 78, photos.plainTawaRoti, "Roti", "Veg"),
      dish("Butter Tawa Roti (4 pcs)", 98, photos.butterTawaRoti, "Roti", "Veg"),
      dish("Lachha Paratha", 38, photos.lachhaParatha, "Roti", "Veg"),
      dish("Tortilla Wrap / Roti", 14, photos.tortillaWrapRoti, "Roti", "Veg"),
      dish("Green Salad", 88, photos.greenSalad, "Salad", "Veg"),
      dish("Onion Salad", 78, photos.onionSalad, "Salad", "Veg"),
    ],
  },
  {
    id: "drinks-desserts",
    name: "Drinks & Desserts",
    eyebrow: "Sip, shake and finish sweet",
    description: "Tea, coffee, coolers, fasting shakes, lassi and ice-cream desserts.",
    cover: photos.oreoColdCoffee,
    items: [
      dish("Milk Tea", 48, photos.milkTea, "Beverages"),
      dish("Masala Milk Tea", 48, photos.masalaMilkTea, "Beverages"),
      dish("Black Tea", 48, photos.blackTea, "Beverages"),
      dish("Lemon Tea", 49, "", "Beverages"),
      dish("Black Coffee", 49, "", "Beverages"),
      dish("Cappuccino Coffee", 58, photos.cappuccinoCoffee, "Beverages"),
      dish("Chocolate Cappuccino", 78, photos.chocolateCappuccino, "Beverages"),
      dish("Cold Coffee", 98, photos.coldCoffee, "Beverages"),
      dish("Chocolate Cold Coffee", 128, photos.chocolateColdCoffee, "Beverages"),
      dish("Oreo Cold Coffee", 138, photos.oreoColdCoffee, "Beverages"),
      dish("Oreo Milk Shake", 128, photos.oreoMilkShake, "Beverages"),
      dish("Vanilla Milk Shake", 138, photos.vanillaMilkShake, "Beverages"),
      dish("Chocolate Milk Shake", 148, photos.chocolateMilkShake, "Beverages"),
      dish("Butterscotch Milk Shake", 148, photos.butterscotchMilkShake, "Beverages"),
      dish("Iced Coke", 68, photos.icedCoke, "Beverages"),
      dish("Masala Coke", 78, photos.masalaCoke, "Beverages"),
      dish("Fresh Lime Juice", 78, photos.freshLimeJuice, "Beverages"),
      dish("Ice Cream Add-on", 30, "", "Beverage Extra", "Add-on"),
      dish("Mix Dry Fruit Shake", 188, photos.mixDryFruitShake, "Fasting Special", "Fasting"),
      dish("Kaju Anjeer Shake", 168, photos.kajuAnjeerShake, "Fasting Special", "Fasting"),
      dish("Banana Milk Shake", 108, photos.bananaMilkShake, "Fasting Special", "Fasting"),
      dish("Mango Milk Shake", 118, photos.mangoMilkShake, "Fasting Special", "Fasting"),
      dish("Sweet Lassi", 78, photos.sweetLassi, "Fasting Special", "Fasting"),
      dish("Gulab Jamun with Ice Cream", 148, photos.gulabJamunIceCream, "Desserts"),
      dish("Vanilla Ice Cream", 78, photos.vanillaIceCream, "Desserts"),
      dish("Chocolate Ice Cream", 88, photos.chocolateIceCream, "Desserts"),
      dish("Butterscotch Ice Cream", 88, photos.butterscotchIceCream, "Desserts"),
    ],
  },
];
